include: package:lint/analysis_options.yaml

linter:
  rules:
    - parameter_assignments

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    missing_required_param: error
    parameter_assignments: error
    missing_return: error
    argument_type_not_assignable: warning
    non_bool_condition: info
    invalid_assignment: info
    return_of_invalid_type: warning
