name: BoilerPlateMVVM
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  stacked:
  stacked_services:
  shared_preferences: ^0.5.12
  flutter_hooks:
  stacked_hooks:
  image_picker:
  cached_network_image: ^2.3.2+1
  get_it: ^4.0.4
  injectable:
  auto_route:
  email_validator:
  animations: ^1.1.1
  http:
  mockito:
  dartz:
  logger:
  permission_handler: ^5.0.1+1
  hive: ^1.4.4
  rxdart:
  hive_flutter: ^0.3.1
  json_serializable: ^3.4.1
  # location: ^3.0.0
  geocoding: ^1.0.4+1
  geolocator: ^6.0.0
  shimmer:
  provider:
  flutter_statusbarcolor:
  freezed_annotation:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.1
  build_runner:
  auto_route_generator:
  injectable_generator:
  lint: ^1.1.1
  freezed:

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
